# ----- WIKI SETUP -----
[basic]
name = "Mast Wiki Engine"
wikipage_directory_prefix = "/wiki/"
image_as_home = false
pinned_pages = [""]

[auth]
users_file = "conf/users.toml"
auth_methods = ["username"] # supported: ["github", "gitlab", "google", "apple", "facebook"]. If empty, users cannot register.
username_signup_requires_email = true
base_user_permission = "r" # rucdas - read, update, create, delete, admin, sudo.

[storage]
type = "local_git"
location = ".wiki/wiki"

# ----- WIKI CUSTOMISATION -----
[shell]
shell = "default"
